# Generated by Django 4.1.4 on 2023-03-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="rooms",
            fields=[
                ("room_no", models.IntegerField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=10)),
                ("no_of_bed", models.IntegerField()),
                ("status", models.CharField(max_length=15)),
            ],
        ),
    ]
