# Generated by Django 4.1.4 on 2023-03-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeedetails",
            name="EMPLOYEE_ID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
