# Generated by Django 4.1.4 on 2023-03-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a_room", models.IntegerField()),
                ("name", models.CharField(max_length=80)),
                ("email", models.CharField(max_length=100)),
                ("checkin", models.DateField()),
                ("checkout", models.DateField()),
            ],
        ),
    ]
