# Generated by Django 4.1.4 on 2023-03-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="mobile_no",
            field=models.BigIntegerField(default=5),
            preserve_default=False,
        ),
    ]
