# Generated by Django 4.1.4 on 2023-03-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employeedetails",
            fields=[
                ("EMPLOYEE_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("EMPLOYEE_NAME", models.CharField(max_length=30)),
                ("DATE_OF_JOINING", models.CharField(max_length=30)),
                ("SALARY", models.DecimalField(decimal_places=3, max_digits=7)),
                ("MOBILE", models.CharField(max_length=10)),
                ("DESIGNATION", models.CharField(max_length=30)),
                (
                    "GENDER",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
            ],
        ),
    ]
