# Generated by Django 4.1.4 on 2023-03-03 05:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="employeedetails",
        ),
    ]
